; Script generated by Antigravity for Snapchat Streak Recoverer
; Use Inno Setup Compiler to compile this script.

#define MyAppName "Snapchat Streak Recoverer"
#define MyAppVersion "1.0"
#define MyAppPublisher "Abdul Haseeb"
#define MyAppURL "https://github.com/abdulhaseeb2k/Snapchat-Streak-Recoverer"
#define MyAppExeName "Snapchat Streak Recoverer.exe"

[Setup]
; App details
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Output folder for the installer
OutputDir=installer_output
OutputBaseFilename=Snapchat_Streak_Recoverer_Setup
PrivilegesRequired=admin
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=assets\APP-ICONE.ico
UninstallDisplayIcon={app}\assets\UNINSTALL-ICONE.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The main executable and all its dependencies from the dist folder
Source: "dist\app\app.exe"; DestDir: "{app}"; DestName: "{#MyAppExeName}"; Flags: ignoreversion
Source: "dist\app\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent
